databases:
  - name: myrailssite
    region: frankfurt
    databaseName: myrailssite
    user: myrailssite

services:
  - type: web
    name: myrailssite
    env: ruby
    region: frankfurt
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myrailssite
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
